name: surfie

on:
  push:
    branches: 
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest code
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer update --ignore-platform-reqs
      - name: Generate key
        run: php artisan key:generate
      - name: Generate storage link
        run: php artisan storage:link
      - name: Set Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.1.1
        with: 
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: afromina_surfie
          DB_USERNAME: afromina_surfieuser
          DB_PASSWORD: lU5Hi8M]Jdzi
        run: vendor/bin/phpunit