name: Deploy to FTP Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"

      - name: Install dependencies
        run: composer install --no-dev

      - name: Build assets
        run: php artisan mix --production

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          server: ftp.afromina-digitals.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./public
          remote-dir: /public_html
